version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: clinica_360_postgres
    environment:
      POSTGRES_USER: clinica_user
      POSTGRES_PASSWORD: clinica_password
      POSTGRES_DB: clinica_360
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinica_user -d clinica_360"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    container_name: clinica_360_api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=clinica_user
      - POSTGRES_PASSWORD=clinica_password
      - POSTGRES_DB=clinica_360
      - POSTGRES_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  postgres_data: 
