version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://clinica360:clinica360@db:5432/clinica360
      - ENVIRONMENT=development
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - db
    networks:
      - clinica360-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=clinica360
      - POSTGRES_USER=clinica360
      - POSTGRES_PASSWORD=clinica360
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clinica360-network
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@clinica360.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - clinica360-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  clinica360-network:
    driver: bridge
