"""Initial migration - create tables

Revision ID: 1ec82a74c38c
Revises: 932bd1aca42b
Create Date: 2025-07-25 19:03:51.870861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec82a74c38c'
down_revision = '932bd1aca42b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 
